server:
  port: 8763
#spring:
#  application:
#    name: client
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&characterSetResults=utf8&autoReconnect=true&failOverReadOnly=false
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.springcloud.cilent.entity

